name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  CI:
    env:
      VENV_DIR: ".venv"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Creating Python Virtual Environment
        run: python3 -m venv "$VENV_DIR"

      - name: Activating Virtual Environment
        run: source "$VENV_DIR/bin/activate"

      - name: Installing Dependencies
        run: pip install --no-cache-dir -r requirements.txt